### ISSUE TITLE
API keys confusing display

### ISSUE THREAD

**Issue by arurke** [FriskByBergen/friskby#10]
In the admin panels, the api-keys are shown in two forms:
1) Without dashes, asdasdasd, e.g. http://friskby.herokuapp.com/admin/api_key/apikey/5
2) With dashes, asd-asd-asd.

The accepted form when posting data is without dashes.

**Comment by arurke** [comment]
Hijacking this to post a valid curl call which might be handy to post as an example:
curl -i -H "Content-type: application/json" -X POST -d '{"sensorid":"sensor_id","timestamp":"2015-11-10T22:32:00Z","value":11,"key":"d6ba65e8-4aa7-4bd8-90bc-df939aaaae99"}' http://friskby.herokuapp.com/sensor/api/reading/

**Comment by joakim-hove** [comment]
Ehh - yes I agree this is slightly confusing; but *both* work. The actual comparison is done here: https://github.com/FriskByBergen/friskby/blob/master/api_key/models.py#L14 - and the `UUID( )` constructor will strip of the dashes internally.

**Comment by arurke** [comment]
Are you sure? I re-tested and get "invalid key" when omitting dashes.

```
curl -i -H "Content-type: application/json" -X POST -d '{"sensorid":"ARUtest","timestamp":"2015-11-10T22:32:00Z","value":11,"key":"d6b065e842a74bd890bcdf939d91de99"}' http://friskby.herokuapp.com/sensor/api/reading/

HTTP/1.1 403 FORBIDDEN
"Invalid key:'d6b065e842a74bd890bcdf939d91de99' when posting to:'ARUtest'"

curl -i -H "Content-type: application/json" -X POST -d '{"sensorid":"ARUtest","timestamp":"2015-11-10T22:32:00Z","value":11,"key":"d6b065e8-42a7-4bd8-90bc-df939d91de99"}' http://friskby.herokuapp.com/sensor/api/reading/

HTTP/1.1 201 CREATED
```

I see now that the page I linked to is actually intended for editing so its probably a bad idea to get the key from there anyway. But maybe update the example on the main page with a dummy key with dashes, or allow keys with and without dashes?
