### ISSUE TITLE
Data fra temp og fukt vises ikke

### ISSUE THREAD

**Issue by njberland** [FriskByBergen/friskby#11]
Vi sender inn data til sensorene 
http://friskby.herokuapp.com/admin/sensor/sensor/STO110Temp/ 
og 
http://friskby.herokuapp.com/admin/sensor/sensor/STO110Humid/
Dataene legges inn i databasen og vi kan se det som feks.
http://friskby.herokuapp.com/admin/sensor/datavalue/210849/

Det rare er at verdiene ikke vises i grafen - men det gjør STO110Dust!

**Comment by njberland** [comment]
Og videre - det er ikke mulig å få opp selve recorden for datavalue som i feks
http://friskby.herokuapp.com/admin/sensor/datavalue/210849/

**Comment by joakim-hove** [comment]
> Og videre - det er ikke mulig å få opp selve recorden for datavalue som i feks

Dette var en skikkelig feil; jeg forstår ikke hva det er - men jobber med saken.

**Comment by joakim-hove** [comment]
> Det rare er at verdiene ikke vises i grafen - men det gjør STO110Dust!

Usikker på om dette er javascript viderverdightere, en variant av det andre problemet, eller noe helt annet. Jeg prioriterer uansett problemet med å få opp DataValue.

**Comment by joakim-hove** [comment]
> Og videre - det er ikke mulig å få opp selve recorden for datavalue som i feks

Fikset: #16
