### ISSUE TITLE
js: Hardcoded device should be removed

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/friskby#110]
It should potentially be removed by improving the API:

https://github.com/FriskByBergen/friskby/blob/master/friskby/static/js/friskby.js#L713

**Comment by joakim-hove** [comment]
Yes!

**Comment by pgdr** [comment]
We should consider moving all these hardcoded values etc. to a `config` object that can live on `window`.  That is, let Django construct the configuration (with e.g. `url=https://friskby.herokuapp.com`, or `url=http://127.0.0.1:8000/`) and put that into `window.config` in js.

**Comment by pgdr** [comment]
With the release and promotion of quick, this is now no longer an issue.
