### ISSUE TITLE
Making the API easier to set up for users...

### ISSUE THREAD

**Issue by njberland** [FriskByBergen/friskby#12]
The API works nice and except for some confusion regarding what "company" means I find it to be understandable...

However - I guess that it will be very hard for students to set up their units and sensors...
Can we make a "configure your device" page to simplify registration for students?

**Comment by joakim-hove** [comment]
>The API works nice and except for some confusion regarding what "company" means I find it to be understandable...

Good; regarding "company" I will remove it - it was a mistake.

> Can we make a "configure your device" page to simplify registration for students?

Yes - absolutely; I have spent quite some time looking into: #11 - but then we can continue with such a page. Such a page will be part of the 'how much / and where to put it' of end-user visible HTML. But I can at least start by putting it 'here'.
