### ISSUE TITLE
Timestamps mandatory?

### ISSUE THREAD

**Issue by arurke** [FriskByBergen/friskby#15]
Are timestamps (suppose to be) mandatory? I vagely remember we discussed having the server add the timestamp if it was missing - and if I understand correctly this code tries to achieve it (?): https://github.com/FriskByBergen/friskby/blob/master/sensor/models.py#L25

In any case I would favor it being optional. It is mandatory now:

```
curl -i -H "Content-type: application/json" -X POST -d '{"sensorid":"ARUtest","value":11,"key":"d6b065e8-42a7-4bd8-90bc-df939d91de99"}' http://friskby.herokuapp.com/sensor/api/reading/

HTTP/1.1 400 BAD REQUEST
"Error: missing fields in payload: ['timestamp']"
```

**Comment by joakim-hove** [comment]
> Are timestamps (suppose to be) mandatory? 

Timestamps are currently mandatory; we discussed that a bit back and forth - and it would of course be simple to change that.

>[...] if I understand correctly this code tries to achieve it (?):

The code you are linking to is the code inserting records in the `RawData` table; in that table there are *two* timestamps - one which is the actual data timestamp, and one which is the timestamp when the data is received on the server - what you point to is the latter.
