### ISSUE TITLE
Quick Highchart Safari support

### ISSUE THREAD

**Issue by oyta** [FriskByBergen/friskby#160]
Some issue on Safari on macOS and iOS. The map is skewed and there are no lines in the chart. I have not gotten around to finding the root cause yet.

**Comment by pgdr** [comment]
Apparently (according to @flikka ) the same thing happens with Chrome on OS~X.  Any known highcharts bugs?  Is there a limit to the number of datapoints it can handle?

**Comment by mortalisk** [comment]
It used to work with the old page. Perhaps it is just some silly little javascript syntax error, like a missing semicolon somewhere.

**Comment by oyta** [comment]
Yes, it should work. I suspect a formatting error om the chart data. I can
try to paste it into a JSON-validator.
tor. 23. feb. 2017 kl. 10.07 skrev Morten Bendiksen <
notifications@github.com>:

**Comment by flikka** [comment]
Hi - a small comment to @pgdr´s comment - on OSX it works in Chrome, but not Safari. On iOS (IPhone SE) it does not work on neither Safari nor Chrome.

There is an error in both Safari and Chrome dev console in the quick.html, the line
```document.getElementById("pmselect").onchange = function(e)```
gives the error
```TypeError: null is not an object (evaluating 'document.getElementById("pmselect")')```

Seems to not be in the DOM. There is another instance of the problem a couple of lines down. No idea if it is relevant to the problem though.

**Comment by pgdr** [comment]
Please reopen if it still doesn't work!

**Comment by mortalisk** [comment]
I think come on ios uses the safari javascript engine, so it kind of makes sense in that case that those combinations don't work.

**Comment by oyta** [comment]
Ref @flikka comment, I also saw that one, but I do not think it is related. I have tested Chrome, Firefox and Safari on macOS and the chart only fails in Safari. @mortalisk comment about the JS-engine seems to be common where it fails.

I have not found the reason though. I have tried to reduce the data set without luck. I ran the JSON through different validators, with no complaints. Testing parts of the code seems fine - but I have not done a step by step live debugging.

**Comment by pgdr** [comment]
Are you able to download a PNG image?

**Comment by oyta** [comment]
I found the issue. Safari (or the JS-engine of Safari) returns NaN in the chart.js function showDataFor: `Date.parse(measurement.timestamp_data)`

Chrome and FF returns the expected value, while Safari does not handle it. I did not find a solution now, but can look into it next time.

**Comment by olavxxx** [comment]
I dont have Apple products to test on, but I have in the past had issues with serving content to Apple-users (different websites), the sollution were either UTF-8 encoding URL or using dataType: 'jsonp'.

**Comment by oyta** [comment]
The JSON is fine, but the JS-engine does not support the 'Date.parse("yyyy-mm-ddThh:mm:ss+zzzz")'. At least that was the result after the late night testing  yesterday :-)

**Comment by mortalisk** [comment]
http://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome

**Comment by oyta** [comment]
Fixed with [#169](https://github.com/FriskByBergen/friskby/pull/169).

**Comment by oyta** [comment]
And with [$171](https://github.com/FriskByBergen/friskby/pull/171)
