### ISSUE TITLE
Midnight data received from BG sensors are interpreted +24h wrong

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/friskby#162]
When we are given data from BG sensors at midnight (say 00:00 the midnight between day 1 and day 2), we interpret the data to belong to next midnight (end of day 2).

**Comment by pgdr** [comment]
I'm quite sure, if `air_in_bergen.py` is still in use, that the offending line is:
```python
current_date = date.today().isoformat()
# ...
ts = current_date + "T" + df[i][tid] + ":00Z"
```

See [air_in_bergen.py#L51](https://github.com/FriskByBergen/friskby/blob/master/friskby/GW/air_in_bergen.py#L51).

In any case, in the database, the following entry can be found:
```
BG_1_PM25";"2017-02-25 00:01:39.195074+01";"2017-02-26 00:00:00+01";14.6;f
```
The first time stamp is `time_recieved` (sic) and the latter is the `timestamp_data`.

If `air_in_bergen.py` is still in use, we should use `datetime.strftime` correctly.

**Comment by oyta** [comment]
Looks good. It would be nice to get correct timestamps on these sensors :)

**Comment by pgdr** [comment]
#180 is a simple fix for now

**Comment by pgdr** [comment]
I think I understand what's wrong now.  It's actually in the line
```python
current_date = date.today().isoformat()
```
that completely ignores timezones, which once a day gives the wrong date compared to the date displayed at luftkvalitet.info.

**Comment by pgdr** [comment]
Okay, this will still be wrong; we need to change the URIs.  If you look at [one sensor](http://www.luftkvalitet.info/home/airquality.aspx?type=2&topic=1&id=%7bceade2ac-e62f-4e50-af7c-347e402fff27%7d), you see that we get a full timestamp, that is, date+time.

If we parse the table with several sensors, we only get the clock, and not the date to which the clock belongs.

That means that if we read the website `2017-03-13T00:01:00` and the website hasn't _updated_ yet, we will read clock `23:00` and a value, and interpret that as `2017-03-13T23:00:00`.  If we received the full timestamp, then we would get `2017-03-12T23:00:00`

Can we change the scraping to a site which exposes the full timestamp?

**Comment by oyta** [comment]
I changed the cron-job (or whatever) in the Friskby admin to run 10-past each hour instead of o-clock. It is not the solution(!), but it may solve the issue is many cases.

**Comment by pgdr** [comment]
> I changed the cron-job (or whatever) in the Friskby admin to run 10-past each hour instead of o-clock. It is not the solution(!), but it may solve the issue is many cases.

Very good!  I thought about something like that (but actually around 15 or even 30 minutes past the hour) yesterday, but couldn't figure out how or where to do it.  I think 10 past works;  we can even verify that in our [rawdata](https://friskby.herokuapp.com/admin/sensor/rawdata/) table; ([e.g.](https://friskby.herokuapp.com/admin/sensor/rawdata/11860085/change/)) `timestamp received: 09:11:40` and `timestamp data: 09:00:00`.

Compare to prior to cron update: ([e.g.](https://friskby.herokuapp.com/admin/sensor/rawdata/11860064/change/)) `timestamp received: 09:01:50` and `timestamp data: 08:00:00`.

@njberland *requested changes to luftkvalitet.info*: it's enough if they simply add the date stamp somewhere (preferably in the table) on their webpage.  As it stands today, it is impossible to know the date of the previous measurement on [Danmarksplass](http://luftkvalitet.info/home/overview.aspx?type=2&topic=1&id={4ff685c1-ad51-4468-b2fc-08345d11f447}).

**Comment by pgdr** [comment]
Seems fixed now,  thanks @oyta
