### ISSUE TITLE
OpenLayers - map stretched initially

### ISSUE THREAD

**Issue by oyta** [FriskByBergen/friskby#167]
<img width="1325" alt="skjermbilde 2017-02-23 kl 22 53 49" src="https://cloud.githubusercontent.com/assets/7596134/23280819/fb38cde2-fa1a-11e6-9e91-9bc68ee20cd5.png">

Resizing the browser window seems to fix the problem. DOM not loaded/ready before loading map?

**Comment by oyta** [comment]
This should be fixed with #171 .

**Comment by oyta** [comment]
Not quite sure, but it seemed like the root cause was that the parent element in the DOM model hadn't specified a width while the child element were based on a percentage.

**Comment by pgdr** [comment]
reopen if necessary.  several patches has been deployed since this was filed.
