### ISSUE TITLE
Remove space character from URLs

### ISSUE THREAD

**Issue by oyta** [FriskByBergen/friskby#168]
The timestamps in the URLs are currently using space between the date and time. Space is not considered valid I believe in the URL (however it is extensively used on the internet). We could change it to ISO8601-std with a T between the date and time? And should the time zone be a part of it?

`http://friskby.herokuapp.com/?start=2017-02-23%2023:00:00&time=2017-03-02%2023:00:00&sensortype=PM10`
Current URLs

`http://friskby.herokuapp.com/?start=2017-02-23T23:00:00+00&time=2017-03-02T23:00:00+00&sensortype=PM10`
Proposed format

**Comment by pgdr** [comment]
Perfect format. datetime.isoformat or whatever it is called in python.

But if &amp; is the "correct" way, I would also prefer you add that simultaneously.

**Comment by mortalisk** [comment]
Does it not have &amp; in the html already?

fre. 24. feb. 2017 kl. 17.17 skrev Pål Grønås Drange <
notifications@github.com>:

**Comment by olavxxx** [comment]
Space is %20 or +, depending on encoder.

24. feb. 2017 6.28 p.m. skrev "Morten Bendiksen" <notifications@github.com>:

**Comment by mortalisk** [comment]
I agree T is better than space (or even %20). And &amp; in the source is the right way to do it.

**Comment by semafor** [comment]
`&` in the [source](view-source:http://friskby.herokuapp.com/) is the start of a character reference, so the browser will try to parse it as such. It's of little consequence as browsers will know what to do, but garden paths probably slow down parsing, so it should be replaced with `&amp;`.
